# 应用服务 WEB 访问端口
server:
  port: 16780
# 应用名称
spring:
  application:
    name: bcu-wallet



# 节点配置
node:
  eth:
    local:
      url: http://localhost:8545
    infura:
      # 此处请填写您的 Infura 地址
      url: https://morden.infura.io/your-token